### ISSUE TITLE
Create a github action to build and upload a wheel

### ISSUE THREAD

**Issue by mattip** [deshaw/pjrmi#2]
Since this repo does not yet have any github actions, could one of the owners please start a blank workflow in order to set up the actions to run? The steps are:
- click on "Actions" between "Pull requests" and "Projects"
- in the next screen, click on "Simple Workflow"
- This will open a `blank.yml` file for editing. Change the name to `wheel.yml`, and then click on the green "commit" button
- Finish the commit, the action should run.

Once that is done, I will submit a PR to finish the wheel building

**Comment by iamsrp-deshaw** [comment]
Done: https://github.com/deshaw/pjrmi/commit/a57e9572ff4e21f28de2ab5a7e2098623e0bf027

Let me know if anything more is needed, or if this can be closed.

srp

**Comment by mattip** [comment]
Thanks!
