### ISSUE TITLE
Jupyter Notebook link is broken for PyPI PJRmi documentation page

### ISSUE THREAD

**Issue by jayantrane** [deshaw/pjrmi#5]
On PyPI documentation page for PJRmi, following hyperlink redirects to non-existent URL.
> As well as the examples below, you can try out the Jupyter [notebook](https://pypi.org/project/pjrmi/python/tests/pjrmi.ipynb) for live versions.

I believe we could make the URL absolute rather than relative to solve this issue.

**Comment by iamsrp-deshaw** [comment]
[Done](https://github.com/deshaw/pjrmi/commit/036a470e741c346ec5b319acf8a16c71f1b3c273), thanks!
